package minitwitter.view;
import minitwitter.controller.AdminController;
import java.sql.Timestamp;
import java.util.*;
import javax.swing.*;

/**
 * JFrame view to represent the regular User interface of
 * the MiniTwitter application.
 * @author Anh Hoang
 */
public class UserView extends javax.swing.JFrame {
    String userID;
    AdminController admin = AdminController.getInstance();

    /**
     * Creates new form UserView
     */
    public UserView(String uid) {
        initComponents();
        ImageIcon img = new ImageIcon(getClass().getClassLoader().getResource("eggFavicon.png"));
        setTitle("User View" + " (" + uid + ")");
        setIconImage(img.getImage());
        userID = uid;
        String feedTitle = userID + "'s News Feed";
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, feedTitle, javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        populateFeed();
        populateFollowingList();
        creationDate.setText("Created: " + admin.getUserCreationTimestamp(uid));
        lastUpdateDate.setText("Last Update: " + admin.getUserCreationTimestamp(uid));
    }

    public void populateFeed() {
        List<String> feedTweets = admin.getNewsFeedFromID(userID);
        DefaultListModel<String> listModel = new DefaultListModel<>();
        for (String tweet : feedTweets) {
            listModel.addElement(tweet + "\n");
        }
        newsFeedListView.setModel(listModel);
    }
    
    public void updateFeed(String tweet) {
        DefaultListModel<String> listModel = (DefaultListModel<String>)newsFeedListView.getModel();
        if (!listModel.contains(tweet)) {
            listModel.addElement(tweet);
            String time = new Timestamp(admin.getLastUpdateTime(userID)).toString();
            lastUpdateDate.setText("Last Update: " + time);
        }
    }

    public void updateFollowerFeeds(String tweet) {
        List<String> followerIDs = admin.getFollowerIDs(userID);
        for (String follower : followerIDs) {
            admin.getUserViewFromID(follower).updateFeed(tweet);
        }
    }

    public void populateFollowingList() {
        List<String> followingList = admin.getFollowingIDs(userID);
        DefaultListModel<String> listModel = new DefaultListModel<>();
        for (String followedUser : followingList) {
            listModel.addElement(followedUser +"\n");
        }
        followingListView.setModel(listModel);
    }
    
    public void updateFollowingList(String followedUser) {
        DefaultListModel<String> listModel = (DefaultListModel<String>)followingListView.getModel();
        if (!listModel.contains(followedUser)) {
            listModel.addElement(followedUser);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        followField = new javax.swing.JTextField();
        followButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        followingListView = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        postTweetContent = new javax.swing.JTextField();
        postTweetButton = new javax.swing.JButton();
        creationDate = new javax.swing.JLabel();
        lastUpdateDate = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        newsFeedListView = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("User View");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Following", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        followField.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        followField.setForeground(new java.awt.Color(40, 40, 40));
        followField.setToolTipText("Enter a user ID to follow.");

        followButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        followButton.setForeground(new java.awt.Color(90, 90, 90));
        followButton.setText("Follow");
        followButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                followButtonActionPerformed(evt);
            }
        });

        followingListView.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        followingListView.setForeground(new java.awt.Color(80, 80, 80));
        followingListView.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(followingListView);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(followField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(followButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(followField)
                    .addComponent(followButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "News Feed", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        postTweetContent.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        postTweetContent.setForeground(new java.awt.Color(40, 40, 40));
        postTweetContent.setToolTipText("Share your thoughts.");

        postTweetButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        postTweetButton.setForeground(new java.awt.Color(90, 90, 90));
        postTweetButton.setText("Post");
        postTweetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postTweetButtonActionPerformed(evt);
            }
        });

        creationDate.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        creationDate.setForeground(new java.awt.Color(120, 120, 120));
        creationDate.setText("<Created: ???>");

        lastUpdateDate.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        lastUpdateDate.setForeground(new java.awt.Color(120, 120, 120));
        lastUpdateDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lastUpdateDate.setText("<Last Updated: ???>");
        lastUpdateDate.setToolTipText("");

        newsFeedListView.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        newsFeedListView.setForeground(new java.awt.Color(80, 80, 80));
        newsFeedListView.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(newsFeedListView);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastUpdateDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(postTweetContent, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(postTweetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(creationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(postTweetButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(postTweetContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(creationDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastUpdateDate)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void postTweetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postTweetButtonActionPerformed
        String tweetMessage = postTweetContent.getText();
        String formattedTweet = admin.postTweet(userID, tweetMessage);
        postTweetContent.setText("");
        updateFeed(formattedTweet);
        updateFollowerFeeds(formattedTweet);
        admin.updateStatByType("Tweets");
        admin.updateStatByType("Positivity");
    }//GEN-LAST:event_postTweetButtonActionPerformed

    private void followButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_followButtonActionPerformed
        String userToFollow = followField.getText().replaceAll("[^a-zA-Z0-9]", "");
        if (admin.getUserFromID(userToFollow) != null && !userToFollow.equals(userID)) {
            admin.followUser(userID, userToFollow);
            followField.setText("");
            updateFollowingList(userToFollow);
        }
    }//GEN-LAST:event_followButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel creationDate;
    private javax.swing.JButton followButton;
    private javax.swing.JTextField followField;
    private javax.swing.JList<String> followingListView;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lastUpdateDate;
    private javax.swing.JList<String> newsFeedListView;
    private javax.swing.JButton postTweetButton;
    private javax.swing.JTextField postTweetContent;
    // End of variables declaration//GEN-END:variables
}
